name: Strategically Important Small Schools
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - folium
  - shapley
  - haversine
  - plotly
  - numpy
  - csv
