name: Strategically Important Small Schools
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - csv
  - math
  - collections
  - folium
  - geopandas
  - numpy
  - pandas
  - plotly.express
  - folium.plugins
  - haversine
  - shapely
  - json
